apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceTypes: ["c3.large","c3.large","c3.large","c3.large"] 
    desiredCapacity: 3
    spot: true

#these are ondemand instances


# 3 type of instances
# 1 - ondemand instances
# 2 - reserved instances
# 3 - spot instances-->